[tool.poetry]
name = "musicquiz"
version = "0.1.0"
description = ""
authors = ["Mateusz"]

[tool.poetry.dependencies]
python = "^3.13.3"
django = "^5.2.2"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"